[project]
name = "picdiredit"
version = "0.1.0"
description = "Small image editing helper tools"
requires-python = ">=3.11"

[project.dependencies]
Pillow = ">=9.0.0"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
